name: Release
on:
  release:
    types:
      - created

jobs:
  publish_on_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@main
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build:linux

  publish_on_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@main
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build:mac

  publish_on_win:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@main
        with:
          node-version: 18
      - name: install dependencies
        run: npm ci
      - name: publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run build:win
